global:
smtp_smarthost: 'smtp.gmail.com:587'
smtp_from: 'austinchang@star-link.tech'
smtp_auth_username: 'austinchang@star-link.tech'
smtp_auth_password: 'AZ2Vgpdr'
smtp_require_tls: true
route:
group_by: ['alertname']
group_wait: 10s
group_interval: 10s
repeat_interval: 10m
receiver: live-monitoring
receivers:
- name: 'live-monitoring'
email_configs:
- to: 'austinchang@star-link.tech'